### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by oleksandriegorov** [aursu/puppet-kubeinstall#1]
Hi Alex, could you please advise on the following questions:
- What kubernetes version is supported?
- What containerd CRI is supported?

**Comment by aursu** [comment]
Initially it was tested on Kubernetes version **1.18.6** (right now it is defined as module default version in `data/common.yaml`).

Please notice, this module initially does not support any update procedure (does not implement https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/ or any other upgrade recommendations). But of course you can just define new version of Kubernetes eg `1.20.1` and Puppet will handle update through RPM via `Package` definition inside `manifests/install.pp` (`kubeinstall::install`).  Not sure it is safe

For the moment it is Docker. I'm going to implement `cri.io` soon but for the moment it is `kubeinstall::runtime::docker` which included into `kubeinstall::install::node` by default

**Comment by aursu** [comment]
> 
> 
> Hi Alex, could you please advise on the following questions:
> 
> - What kubernetes version is supported?
> 
> - What containerd CRI is supported?

If this Q is still relevant:)

Version 1.21.2 (not 1.22 because Cri-O is still 1.21)

Cri-O is default CRI, Docker is still included as an option

Upgrade is still not implemented and I'm going to use Bolt task to include this into module (Puppet is not good tool to use it for k8s upgrade)
